import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ClerkLoaded, ClerkLoading, ClerkProvider } from "@clerk/nextjs";
import Loader from "@/components/Loader";
// import Providers from "@/components/Providers";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Soumya Agrawal app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ClerkLoading>
            <Loader />
          </ClerkLoading>
          <ClerkLoaded>
            <Header />
            {/* <Providers> */}
            {children}
            {/* </Providers> */}
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
//layout is the wrapper of the page
//pages can have their own layouts or a common layout
// no head tag, so the title and description can be fetched from metadata and be viewed in page source
// children refers to paged and anything above or below it will be common to all renders
//RootLayout function name can be changed
// Layout is for all pages-custom layout.jsx,page.jsx
//@- src folder check in jsconfig.json file
// can create custom components and can be used as common in layout.jsx
//Main layout wraps-specific layout - wraps respective page
//Every page can have own loading.jsx and not-found.jsx
// Empty files cannot be created in app folder
// Public folder or custom folder for images but next imports images as objects so use image.src
// For remote images, specify which remote images are allowed
// use client componenets instead of complete client router pages
